---
abstract: 'Tapper - Common functionality for remote automation libs'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Remote
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Path: 0
  Getopt::Long: 0
  IO::Socket::INET: 0
  Moose: 0
  Net::TFTP: 0.19
  Socket: 0
  Sys::Hostname: 0
  Tapper::Base: 3.000001
  YAML::Syck: 0
version: 3.000001
